### ISSUE TITLE
W3C DOM Firing Events Section Missing JS Realm Security Assurances

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/dom#10]
Comparing:

- http://www.w3.org/TR/domcore/#firing-events
- https://dom.spec.whatwg.org/#concept-event-fire

Per @marcoscaceres in https://github.com/w3c/manifest/issues/526:

> There is new behavior and security assurances (related to things being in the correct JS realm, etc.) in the WHATWG DOM spec that we rely on.

**Comment by zqzhang** [comment]
These 2 commits are related:

- [ ] https://github.com/whatwg/dom/commit/5f39374 Use the relevant realm of the event target when firing an event
- [ ] https://github.com/whatwg/dom/commit/e19d7ee Redesign fire an event and target override

**Comment by yongsheng** [comment]
dependency on  #17 .

**Comment by yongsheng** [comment]
'fire an event' is used for shadow dom. so leave it until shadow dom is fixed.

**Comment by RobDolinMS** [comment]
@zqzhang @yongsheng Would you please explain why this was closed?

Is this now fixed thanks to #17 or something else?

**Comment by yongsheng** [comment]
I believe it's been in 4.1 now.

**Comment by zqzhang** [comment]
This shall be fixed by https://github.com/w3c/dom/commit/c18f6aa3c5c6ff9fbbf02c1d222bcdf57e5f6b6c

**Comment by marcoscaceres** [comment]
Just fyi, the manifest spec is tracking WHATWG DOM instead. It might be good to migrate all specs to point to WHATWG DOM too, as to avoid further confusion.
