### ISSUE TITLE
<span class="a b c">.classList.replace("c", "a") -> "a b" or "b a"?

### ISSUE THREAD

**Issue by ayg** [w3c/dom#117]
The spec just says "Replace token in tokens with newToken", but this doesn't actually work in an ordered set, because if you actually replaced it as instructed, the set would have a duplicate entry.  Test-case:

```html
data:text/html,<!doctype html>
<script>
var span = document.createElement("span");
span.setAttribute("class", "a b c");
span.classList.replace("c", "a");
document.documentElement.textContent = span.getAttribute("class");
</script>
```

Firefox Aurora says "a b".  Chrome doesn't seem to support .replace().  I don't have Edge or WebKit handy yet to test.

**Comment by linzhiping** [comment]
I tested with Safari 10.1, it say "a b" too, same as FireFox.

**Comment by yongsheng** [comment]
thanks, @linzhiping . I think we'll add it in DOM4.1. @chaals

**Comment by zqzhang** [comment]
This shall be fixed.
