### ISSUE TITLE
Custom Elements in DOM

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#14]
If Custom Elements is implemented in a second browser, we need to determine how to integrate it into the DOM specification.

In the end, the DOM specification shall align with the HTML specification on this feature integration at https://github.com/w3c/html/issues/569.

WHATWG has made (up to Dec. 30, 2016) the following changes related to integrating Custom Elements:

- [ ] https://github.com/whatwg/dom/commit/3536dd9 Editorial: update custom element cross-spec references
- [ ] https://github.com/whatwg/dom/commit/d077da1 Don't set custom element state redundantly
- [ ] https://github.com/whatwg/dom/commit/00250fc Fix example of "undefined" custom element state
- [ ] https://github.com/whatwg/dom/commit/182e89f Clarify that the namespace check in "create an element" is redundant
- [ ] https://github.com/whatwg/dom/commit/539e452 Set the stage for preventing double custom element constructor calls
- [ ] https://github.com/whatwg/dom/commit/674e934 Set the stage for new custom element adoption semantics
- [ ] https://github.com/whatwg/dom/commit/766a5e7 Remove incorrect customized built-in element checks

**Comment by yongsheng** [comment]
HTML5.1 doesn't include changes related to custom element.  I don't think it should be fixed in DOM 4.1.https://www.w3.org/TR/html51/index.html#contents

**Comment by chaals** [comment]
Yeah, my current expectation is that it won't be included in HTML 5.2, but probably will in HTML 5.3.

So it is probably worth thinking about what it would involve…

**Comment by xfq** [comment]
https://github.com/w3c/dom/commit/fcd248e63a2b399b21ca00fffaa94206cd74a059 added support for custom elements. Can we close this issue and track specific issues related to custom elements by filing new issues, @yongsheng?

**Comment by yongsheng** [comment]
yes, i think so since it's been in the 4.2 now.
