### ISSUE TITLE
Add DOM childnode methods: prepend(), append(), before(), after() and replaceWith()

### ISSUE THREAD

**Issue by wolfbeast** [w3c/dom#156]
See: https://dom.spec.whatwg.org/#interface-childnode

This is used in the wild (e.g. lazy loading uses replaceWith regularly). it should be in the DOM spec.

**Comment by zqzhang** [comment]
This shall have been fixed. See https://w3c.github.io/dom/#interface-childnode

**Comment by zqzhang** [comment]
By the way, `prepend()` and `append()` are specified in https://w3c.github.io/dom/#interface-parentnode

If the current being spec is OK, please close this issue, thanks.

**Comment by wolfbeast** [comment]
Any time frame when this will become standards track?
