### ISSUE TITLE
Shadow DOM support in DOM spec

### ISSUE THREAD

**Issue by hmin** [w3c/dom#16]
[Shadow DOM](https://www.w3.org/TR/shadow-dom/)[1] is still in the progress of being upstreamed to DOM standard and its relevant specifications. As stated by [WHATWG-DOM](https://dom.spec.whatwg.org/)[2], there are already many commits to add shadow DOM support in the specification. According to [MDN-Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM)[3] informative reference, currently shadow DOM is being implemented by one UA (Chrome 53+) at the moment Jan 2017.

Shadow DOM is finally expected to be upstreamed into DOM standard, and the following commits from WHATG-DOM[2] will be taken into considerations for shadow changes:

- [ ] https://github.com/whatwg/dom/commit/018440e Editorial: add sections on document and shadow trees	
- [ ] https://github.com/whatwg/dom/commit/7dae99c Editorial: define in a shadow-including document and shadow-including…  …	
- [ ] https://github.com/whatwg/dom/commit/9c00ee2 Editorial: introduce more shadow-including terms for CSS  …
- [ ] 	https://github.com/whatwg/dom/commit/b4cc543 Editorial: shadow-including rather than shadow-root-including  …
- [ ] 	https://github.com/whatwg/dom/commit/443023a Editorial: stop enumerating ShadowRoot alongside DocumentFragment  …	
- [ ] https://github.com/whatwg/dom/commit/fdad8cb Shadow: <slot> is now defined in HTML	
- [ ] https://github.com/whatwg/dom/commit/fbc0c31 Shadow: add "retargeting steps" to the dispatch algorithm  …	
- [ ] https://github.com/whatwg/dom/commit/4183385 Shadow: add DocumentOrShadowRoot mixin  …	
- [ ] https://github.com/whatwg/dom/commit/b2ee400 Shadow: add shadow root  …
- [ ] https://github.com/whatwg/dom/commit/810cce8 Shadow: add ShadowRoot's mode attribute  …	
- [ ] https://github.com/whatwg/dom/commit/2153769 Shadow: adjust composedPath() when currentTarget is a Window object  …
- [ ] https://github.com/whatwg/dom/commit/1699495 Shadow: define .attachShadow() and .shadowRoot
- [ ] https://github.com/whatwg/dom/commit/b8e1ccf Shadow: define assignedSlot of Element and Text	
- [ ] https://github.com/whatwg/dom/commit/b8d2854 Shadow: define attachShadow() for custom elements	
- [ ] https://github.com/whatwg/dom/commit/ed94c9f Shadow: define event retargeting for shadow trees  …
- [ ] https://github.com/whatwg/dom/commit/58b19e4 Shadow: define Event's composedPath()  …	
- [ ] https://github.com/whatwg/dom/commit/ef69a24 Shadow: define event's relatedTarget handling  …
- [ ] https://github.com/whatwg/dom/commit/81566a3 Shadow: define slotchange event  …	
- [ ] https://github.com/whatwg/dom/commit/a2b04df Shadow: define slots and slotables	
- [ ] https://github.com/whatwg/dom/commit/e3d8291 Shadow: define superglobal slot content attribute  …	
- [ ] https://github.com/whatwg/dom/commit/afac504 Shadow: do not dispatch an event when target is reletedTarget  …	
- [ ] https://github.com/whatwg/dom/commit/76fbe55 Shadow: fix shadow-including root  …	
- [ ] https://github.com/whatwg/dom/commit/25b6110 Shadow: include shadow trees when adopting  …	
- [ ] https://github.com/whatwg/dom/commit/ca0f853 Shadow: rename "unclosed node"  …	
- [ ] https://github.com/whatwg/dom/commit/2d5aaed Shadow: run insertion and removing steps also for shadow trees  …	
- [ ] https://github.com/whatwg/dom/commit/b3571d7 Shadow: safelist "main" in attachShadowRoot()  …	
- [ ] https://github.com/whatwg/dom/commit/89a849a Shadow: stop re-signaling a slotchange event  …	
- [ ] https://github.com/whatwg/dom/commit/ce21cb5 Shadow: update the definition of an unclosed node  …	

Any comments of shadow dom spec and its progress are appreciated.

[1] https://www.w3.org/TR/shadow-dom/
[2] https://dom.spec.whatwg.org/
[3] https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM

**Comment by yongsheng** [comment]
All, any comments about this?

**Comment by chaals** [comment]
Let's have *one* of this and #13 open since they are duplicates.

It looks like Webkit is implementing, but we need to check what actually gets implemented.
