### ISSUE TITLE
EventTarget: Add EventListenerOptions / AddEventListenerOptions

### ISSUE THREAD

**Issue by RByers** [w3c/dom#17]
See design discussion in [WICG repo](https://github.com/WICG/EventListenerOptions/blob/gh-pages/README.md) and [existing spec text](https://dom.spec.whatwg.org/#dictdef-eventlisteneroptions).  Currently [implemented](http://caniuse.com/#feat=passive-event-listener) in WebKit, Blink and Gecko.

**Comment by yongsheng** [comment]
yes, we'll add it in DOM4.1.

**Comment by zqzhang** [comment]
Related changes against event listeners:

- [ ] https://github.com/whatwg/dom/commit/253a21b Add EventListenerOptions and passive event listener feature
- [ ] https://github.com/whatwg/dom/commit/1ff10ba Define that event listener capture
- [ ] https://github.com/whatwg/dom/commit/e002d78 Enable an event listener to be invoked just once
- [ ] https://github.com/whatwg/dom/commit/a13a3c7 Remove passive as event listener key
- [ ] https://github.com/whatwg/dom/commit/2185b63 Editorial: define defaults for EventListenerOptions
- [ ] https://github.com/whatwg/dom/commit/5324200 Address reentrancy issue with "once" listeners
- [ ] https://github.com/whatwg/dom/commit/806d4aa Unset stop propagation flags after dispatch
- [ ] https://github.com/whatwg/dom/commit/04b1837 Minor rewording of non-normative addEventListener() text.
- [ ] https://github.com/whatwg/dom/commit/02710dd event listeners can be removed but not added during invocation

**Comment by yongsheng** [comment]
02710dd not sure to be fixed in DOM 4.1, any idea?

**Comment by yongsheng** [comment]
I'll take it and fix it.
