### ISSUE TITLE
Dispatching events: Integrate changes for invoking an object, etc.

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#19]
Still not sure whether to integrate these related commits:

- [ ] https://github.com/whatwg/dom/commit/cb12fd4 Define special dispatch behavior for click events
- [ ] https://github.com/whatwg/dom/commit/82692b9 Editorial: rename activation-behavior-related algorithms
- [ ] https://github.com/whatwg/dom/commit/d8cb495 Clean up the event dispatch algorithms
- [ ] https://github.com/whatwg/dom/commit/26f7947 do not invoke target while iterating eventPath
- [ ] https://github.com/whatwg/dom/commit/a768d8e Editorial: check stop propagation flag at start of invoke

All comments are welcome.

**Comment by yongsheng** [comment]
- [ ] https://github.com/whatwg/dom/commit/26f7947 Fix #169: do not invoke target while iterating eventPath

**Comment by yongsheng** [comment]
I think most of them should be fixed in DOM4.1.

**Comment by yongsheng** [comment]
This issues depends on #17 . Need to fix them together. I'll take it.

**Comment by zqzhang** [comment]
OK, thanks, @yongsheng

**Comment by yongsheng** [comment]
- [ ] https://github.com/whatwg/dom/commit/e728c11 Editorial: provide a shorthand for other specifications to create events  …

**Comment by chaals** [comment]
I think it would be good to deal with the synthetic click cleanups, here and in HTML…

**Comment by yongsheng** [comment]
together with #17.

**Comment by yongsheng** [comment]
@chaals what do you mean about 'synthetic click cleanup'? what's for HTML?

**Comment by xfq** [comment]
#17 has been closed, what about this one? Is it fixed now?

**Comment by zqzhang** [comment]
This shall be fixed. Close it.
