### ISSUE TITLE
DOMTokenList: integrate changes against DOMTokenList

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#20]
- [ ] https://github.com/whatwg/dom/commit/ff4f0e8 remove feature detection from add() and add supports()
- [ ] https://github.com/whatwg/dom/commit/a97debc DOMTokenList's supports() takes a single token
- [ ] https://github.com/whatwg/dom/commit/b023e59 fix minor typo
- [ ] https://github.com/whatwg/dom/commit/6d3076e Make DOMTokenList's contains() not throw
- [ ] https://github.com/whatwg/dom/commit/cb85ac4 Editorial: simplify DOMTokenList IDL
- [ ] https://github.com/whatwg/dom/commit/e48ced4 DOMSettableTokenList has an associated attribute too
- [ ] https://github.com/whatwg/dom/commit/4674ad0 Add DOMTokenList hook to validate to added token
- [ ] https://github.com/whatwg/dom/commit/244f66f use less loops
- [ ] https://github.com/whatwg/dom/commit/ad73dc5 DOMTokenList has an associated attribute's local name
- [ ] https://github.com/whatwg/dom/commit/ff81234 Attempt to generalize the DOMTokenList requirements
- [ ] https://github.com/whatwg/dom/commit/2920fc1 sad DOMTokenList serialization is sad
- [ ] https://github.com/whatwg/dom/commit/f7dfc82 introduce DOMTokenList's replace()
- [ ] https://github.com/whatwg/dom/commit/63a0302 Add a validation step when a new DOMTokenList is created

**Comment by yongsheng** [comment]
part of this commit about DOMTokenList should be addressed as well: https://github.com/whatwg/dom/commit/4b291d1
