### ISSUE TITLE
Document.createAttribute(NS): add these 2 methods?

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#21]
- [ ] https://github.com/whatwg/dom/commit/522710bc4be13d2e1d826f94c54d1de9956ec920 Add createAttribute and createAttributeNS :-(
- [ ] https://github.com/whatwg/dom/commit/b525966512a7866d42ba6ab889db4c90b547231b make createAttribute() lowercase the input in HTML documents

**Comment by yongsheng** [comment]
Miss one fix:
- [ ] https://github.com/whatwg/dom/commit/b525966 Fix #41: make createAttribute() lowercase the input in HTML documents

**Comment by yongsheng** [comment]
Need to confirm whether to add it based on user agents' implementation.
