### ISSUE TITLE
 [CEReactions]: Integrate changes against IDL extended attribute

### ISSUE THREAD

**Issue by linzhiping** [w3c/dom#22]
- [ ] https://github.com/whatwg/dom/commit/3cd02d1 Add [CEReactions] annotations to mutating methods
- [ ] https://github.com/whatwg/dom/commit/189d879 insertAdjacentText() does not need [CEReactions]
- [ ] https://github.com/whatwg/dom/commit/bf1c902 Mark Element's slot IDL attribute [Unscopable]
Include other changes related to CEReactions.

**Comment by yongsheng** [comment]
cereactions is for custom element and won't be introduced until custom element is supported.

**Comment by xfq** [comment]
Custom elements support are added in https://github.com/w3c/dom/commit/fcd248e63a2b399b21ca00fffaa94206cd74a059

Will [CEReactions] be integrated in DOM 4.1? Or defer it to DOM 4.2?

**Comment by yongsheng** [comment]
wucongdonglai will fix it soon.
