### ISSUE TITLE
Mutation observers: refine the notification steps and clarify "Transient registered observers"

### ISSUE THREAD

**Issue by linzhiping** [w3c/dom#31]
- [ ] https://github.com/whatwg/dom/commit/d4ca217 Do not let mutation observer callbacks influence the used signal slot
- [x] https://github.com/whatwg/dom/commit/e57a716 Add a note explaining transient observers.

**Comment by yongsheng** [comment]
- [ ] https://github.com/whatwg/dom/commit/f2427d8 Clarify initial state of "mutation observer compound microtask queued…
Better to split this fix into two commits since there are 2 different things. another is for 'MutationRecord'.

**Comment by linzhiping** [comment]
https://github.com/whatwg/dom/commit/d4ca217
Signal slot is introduced by shadow dom? It will be ignored if so.

**Comment by linzhiping** [comment]
Fixed in patch: https://github.com/w3c/dom/commit/26e6a3b
Paste here, since a typo in commit message caused no auto generated commit link.
