### ISSUE TITLE
Interface Element: refine the description of element creation.

### ISSUE THREAD

**Issue by linzhiping** [w3c/dom#37]
- [ ] https://github.com/whatwg/dom/commit/6b1b1da Mark more elements in browsing-context-less documents as "undefined"
- [ ] https://github.com/whatwg/dom/commit/eb28710 Change createElement to report exceptions instead of rethrowing

**Comment by linzhiping** [comment]
This issue tries to improve the steps of "to create an element", both custom element related.
Custom element won't be introduced until custom element is supported.

**Comment by yongsheng** [comment]
merge it into #49.
