### ISSUE TITLE
Interface Node: Make Attr inherit from Node again

### ISSUE THREAD

**Issue by linzhiping** [w3c/dom#58]
- [ ] https://github.com/whatwg/dom/commit/625a074 Make Attr inherit from Node again
- [ ] https://github.com/whatwg/dom/commit/f64b0c8 Put Attr.prototype.ownerElement back; give Attr.prototype.value a setter and an alias named textContent

**Comment by linzhiping** [comment]
There are already 2 issues about Attr Node, for reference:
https://github.com/w3c/dom/issues/4
https://github.com/w3c/dom/issues/5

**Comment by wucongdonglai** [comment]
please take care of https://github.com/whatwg/dom/commit/2b76ab8

**Comment by yongsheng** [comment]
tried in chrome and firefox, below 2 statements return 'true':
document.children[0].attributes[0] instanceof Node
document.children[0].attributes[0] instanceof Attr

**Comment by yongsheng** [comment]
@linzhiping maybe I can fix this issue since #29 depends on it?

**Comment by yongsheng** [comment]
@wucongdonglai Attr.nodeValue is deprecated. see https://dom.spec.whatwg.org/#interface-attr.

**Comment by yongsheng** [comment]
related to #77
