### ISSUE TITLE
Move DOMException into IDL and remove DOMError

### ISSUE THREAD

**Issue by wucongdonglai** [w3c/dom#61]
- [ ] https://github.com/whatwg/dom/commit/3287ee4 Improve warnings in Errors section.
- [ ] https://github.com/whatwg/dom/commit/7fe5736 DOMException is in IDL. DOMError removed

**Comment by yongsheng** [comment]
this is invalid since our base has no DOMError definition. we reference the DOMException defined in WebIDL.
