### ISSUE TITLE
ChildNode:Make after/before/replaceWith work when the context object is passed as argument

### ISSUE THREAD

**Issue by wucongdonglai** [w3c/dom#65]
- [ ] https://github.com/whatwg/dom/commit/4c44562 Make after/before/replaceWith work when the context object is passed as argument.

**Comment by kurli** [comment]
Please remove Fixes

**Comment by yongsheng** [comment]
link should be https://github.com/whatwg/dom/commit/30ab74.
close it and fix it together with #64
