### ISSUE TITLE
Element & Document:add webkitMatchesSelector() in Element and rename legacy alias to historical alias in Document

### ISSUE THREAD

**Issue by jinhoward** [w3c/dom#69]
- [ ] https://github.com/whatwg/dom/commit/9ac9c15 Add webkitMatchesSelector() and rename legacy alias to historical alias to remain consistent with other historical annotations.

**Comment by yongsheng** [comment]
both Firefox and chrome support it. fix it in M4.

**Comment by yongsheng** [comment]
@chaals @siusin the method has a 'webkit' prefix, though it's implemented in firefox and chrome,  do you think it's ok to add it into DOM 4.1?

**Comment by siusin** [comment]
Should be OK if there are 2+ implementations.

**Comment by yongsheng** [comment]
merge it to #79
