### ISSUE TITLE
Define document's origin slot in DOM rather than HTML

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#74]
- [ ] https://github.com/whatwg/dom/commit/e4b7778

**Comment by zqzhang** [comment]
`document.origin` is only supported by Chrome. It hasn't been supported by Firefox, IE, Safari or Opera.

So I don't think we shall define it in DOM 4.1 at current being.

What do you think? @yongsheng

**Comment by zqzhang** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/API/Document/origin

**Comment by yongsheng** [comment]
The problem is, how do developers get it?
seems developers can get via document.defaultView.location.origin in firefox.

**Comment by zqzhang** [comment]
@yongsheng actually, your fix at https://github.com/w3c/dom/commit/fffe5f1eabde1c32734ff08eced3cf076b9a83aa for #45 has been fixed this issue too.

The only difference is that https://github.com/whatwg/dom/commit/e4b7778 uses `for=Document` to define document's origin slot in DOM, and your fix uses `<a href="#concept-document-origin">`.

So let's close this issue directly if you agree.

**Comment by yongsheng** [comment]
agree.
