### ISSUE TITLE
Node: ATTRIBUTE_NODE and SHOW_ATTRIBUTE are no longer historical

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#77]
- [ ] https://github.com/whatwg/dom/commit/dc3990d
- [ ] https://github.com/whatwg/dom/commit/625a074 Make Attr inherit from Node again
- [ ] https://github.com/whatwg/dom/commit/f64b0c8 Put Attr.prototype.ownerElement back; give Attr.prototype.value a setter and an alias named textContent

**Comment by yongsheng** [comment]
it'll be done in M3.
