### ISSUE TITLE
Element: closest() and matches()

### ISSUE THREAD

**Issue by zqzhang** [w3c/dom#79]
- [ ] https://github.com/whatwg/dom/commit/fd69cc7 Add Element.prototype.closest(selectors)
- [ ] https://github.com/whatwg/dom/commit/5ff8f79 Define :scope element for closest() and matches()
- [ ] https://github.com/whatwg/dom/commit/9ac9c15 Add webkitMatchesSelector() and rename legacy alias to historical alias to remain consistent with other historical annotations.

**Comment by yongsheng** [comment]
#69 depends on it.

**Comment by zqzhang** [comment]
OK, thanks, @yongsheng
