### ISSUE TITLE
Mutation algorithms:Replacing a child within parent had the wrong previousSibling in its mutation record 

### ISSUE THREAD

**Issue by wucongdonglai** [w3c/dom#82]
- [x] https://github.com/whatwg/dom/commit/d9fbd12 Replacing a child within parent had the wrong previousSibling in its mutation record Fixes #59 
- [x] https://github.com/whatwg/dom/commit/5aecfd4 Since node can be child, record the previous sibling before adopting Fixes #59 (again).

**Comment by yongsheng** [comment]
Missing one commit:
- [ ] https://github.com/whatwg/dom/commit/c20e4b5 Do not remove child from its parent when replacing a node by itself

**Comment by yongsheng** [comment]
close this issue since it's realted to #25. will change it there.
