### ISSUE TITLE
Serviceworker: align with the latest serviceworker spec?

### ISSUE THREAD

**Issue by yongsheng** [w3c/dom#94]
Not sure it should be included in 4.1. Welcome your comments.
- [ ] https://github.com/whatwg/dom/commit/5666670 Close #155: change addEventListener()/removeEventListener() for service workers.

**Comment by chaals** [comment]
I believe there is a fair bit of implementation, so we probably should include it. Especially if we are going to push the timeline for Shadow DOM - see #150 ...
